#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy  to AWS ElasticBeanstalk
#---------------------------------------------------------------------


name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "headversity-projectj"
  EB_APPLICATION_NAME       : "myheadveristy"
  EB_ENVIRONMENT_NAME       : "Myheadveristy-env"
  AWS_REGION_NAME           : "us-east-1"
  
  on:
  push:
    branches: 
    - master
     
  steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
    - name: Setup .NET 6.0.x

      uses: actions/setup-dotnet@v1

      with:

        dotnet-version: 6.0.x
---
  name: "Restore dependencies"
   
   run: dotnet restore
   
   - name: Publish application        

   run: dotnet publish --output publish --configuration Release --framework net6.0 --runtime win-x64 --self-contained true

- name: ZIP built application      

   run: |

        cd ./publish

        zip -r ${{ env.ZIP_FILE }} .

        mv ./${{ env.ZIP_FILE }} ../

        cd ../           

   env:   

               ZIP_FILE: "headversityj2.zip"


- name: Configure AWS credentials

      uses: aws-actions/configure-aws-credentials@v1

      with: "headversityj2.zip"

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: ${{ env.AWS_REGION }}


 - name: Copy ZIP file into AWS S3 bucket

      run: aws s3 cp ${{ env.ZIP_FILE }} s3://${{ env.AWS_BUCKET }}

      env:

        ZIP_FILE: "headversityj2.zip"
